services:
  postgres:
    image: postgres:16-alpine
    container_name: paperpilot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperpilotdb
      POSTGRES_USER: paperpilot
      POSTGRES_PASSWORD: "111111"
    ports:
      - "5432:5432"
    volumes:
      - paperpilot_postgres_data:/var/lib/postgresql/data

volumes:
  paperpilot_postgres_data:
